#!/usr/bin/env python3

"""
USAGE:
    cd codegen/bin
    python3 hermes_run_config.py

OUTPUT:
    ${HERMES_RUN}/src/config_client_default.h (if client)
    ${HERMES_RUN}/src/config_server_default.h (if server)
"""

from codegen.hermes_run_config.generator import create_config
from codegen.util.paths import HERMES_RUN_ROOT

create_config(
    path=f"{HERMES_RUN_ROOT}/config/hermes_run_client_default.yaml",
    var_name="kHermesRunClientDefaultConfigStr",
    config_path=f"{HERMES_RUN_ROOT}/include/hermes_run/config/config_client_default.h",
    macro_name="CLIENT"
)

create_config(
    path=f"{HERMES_RUN_ROOT}/config/hermes_run_server_default.yaml",
    var_name="kHermesRunServerDefaultConfigStr",
    config_path=f"{HERMES_RUN_ROOT}/include/hermes_run/config/config_server_default.h",
    macro_name="SERVER"
)